In [1]:
from csh_fantasy_bot import bot
from csh_fantasy_bot.yahoo_scraping import YahooPredictions, PredictionType

league_id = "411.l.85094"
manager: bot.ManagerBot = bot.ManagerBot(league_id=league_id)

In [2]:
draft_results = manager.lg.draft_results(format='Pandas')

draft_results

,draft_pick,draft_round,team_key,player_key,fantasy_team_id
player_id,,,,,
6743,1,1,411.l.85094.t.6,411.p.6743,6
6369,2,1,411.l.85094.t.10,411.p.6369,10
5980,3,1,411.l.85094.t.5,411.p.5980,5
5425,4,1,411.l.85094.t.1,411.p.5425,1
5699,5,1,411.l.85094.t.2,411.p.5699,2
...,...,...,...,...,...
8643,188,16,411.l.85094.t.2,411.p.8643,2
7636,189,16,411.l.85094.t.1,411.p.7636,1
4974,190,16,411.l.85094.t.5,411.p.4974,5
6762,191,16,411.l.85094.t.10,411.p.6762,10
3349,192,16,411.l.85094.t.6,411.p.3349,6

In [3]:
y_projections = YahooPredictions(league_id, predition_type=PredictionType.rest_season)
y_projections

Logging in

INFO:csh_fantasy_bot.yahoo_scraping:Setting username: craig_hamilton2000@yahoo.com
/Users/craigh/dev/fantasy_bot/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py:393: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [4]:
projected_draft = draft_results.merge(y_projections.all_players[['preseason_rank', 'current_rank','name'] + manager.lg.scoring_categories()], left_index=True, right_index=True)

In [12]:
projected_draft['draft_value'] = projected_draft['pick'] - projected_draft['current_rank']
projected_draft['draft_value_clipped_30'] = projected_draft['draft_value'].clip(-30,30)
projected_draft['draft_value_clipped_50'] = projected_draft['draft_value'].clip(-50,50)
projected_draft[projected_draft.pick < 25]

# projected_draft.current_rank.dtype

,pick,round,team_key,player_key,fantasy_team_id,preseason_rank,current_rank,name,G,A,+/-,PPP,SOG,HIT,draft_value,draft_value_clipped,draft_value_clipped_30,draft_value_clipped_50
player_id,,,,,,,,,,,,,,,,,,
6743,1,1,411.l.85094.t.6,411.p.6743,6,1,1,Connor McDavid,0.512195,0.951219,0.268293,0.634146,3.487805,0.951219,0,0,0,0
6369,2,1,411.l.85094.t.10,411.p.6369,10,2,2,Leon Draisaitl,0.575000,0.825000,0.237500,0.512500,3.187500,0.700000,0,0,0,0
5980,3,1,411.l.85094.t.5,411.p.5980,5,3,3,Nathan MacKinnon,0.507246,0.782609,0.246377,0.521739,4.420290,0.753623,0,0,0,0
5425,4,1,411.l.85094.t.1,411.p.5425,1,4,17,Nikita Kucherov,0.500000,0.843750,0.312500,0.578125,3.015625,0.531250,-13,-13,-13,-13
7109,6,1,411.l.85094.t.11,411.p.7109,11,10,5,Auston Matthews,0.739726,0.479452,0.315068,0.315068,4.205480,0.931507,1,1,1,1
6391,7,1,411.l.85094.t.12,411.p.6391,12,8,7,David Pastrnak,0.586667,0.613333,0.226667,0.453333,3.706667,0.720000,0,0,0,0
6752,8,1,411.l.85094.t.9,411.p.6752,9,7,8,Mikko Rantanen,0.565789,0.684211,0.236842,0.486842,3.236842,0.552632,0,0,0,0
6728,9,1,411.l.85094.t.8,411.p.6728,8,6,9,Artemi Panarin,0.423077,0.948718,0.346154,0.384615,2.769231,0.294872,0,0,0,0
4351,10,1,411.l.85094.t.4,411.p.4351,4,11,6,Brad Marchand,0.532468,0.740260,0.324675,0.350649,2.948052,1.103896,4,4,4,4
3637,11,1,411.l.85094.t.7,411.p.3637,7,12,11,Alex Ovechkin,0.594937,0.417722,-0.126582,0.316456,4.025316,2.443038,0,0,0,0
7519,12,1,411.l.85094.t.3,411.p.7519,3,13,35,Cale Makar,0.191781,0.780822,0.205479,0.438356,2.315068,1.054795,-23,-23,-23,-23
4240,13,2,411.l.85094.t.3,411.p.4240,3,9,16,Patrick Kane,0.444444,0.703704,0.049383,0.370370,3.604938,0.246914,-3,-3,-3,-3
6746,14,2,411.l.85094.t.7,411.p.6746,7,14,13,Mitchell Marner,0.353659,0.853659,0.231707,0.329268,2.865854,0.402439,1,1,1,1
5364,15,2,411.l.85094.t.4,411.p.5364,4,15,14,Jonathan Huberdeau,0.365854,0.743902,0.158537,0.439024,2.353658,0.878049,1,1,1,1
6448,16,2,411.l.85094.t.8,411.p.6448,8,18,28,Brayden Point,0.412500,0.600000,0.325000,0.300000,2.325000,0.400000,-12,-12,-12,-12
6777,17,2,411.l.85094.t.9,411.p.6777,9,17,23,Sebastian Aho,0.437500,0.600000,0.175000,0.325000,2.750000,0.762500,-6,-6,-6,-6
5367,20,2,411.l.85094.t.2,411.p.5367,2,19,30,Mika Zibanejad,0.466667,0.493333,0.066667,0.346667,3.173333,1.306667,-10,-10,-10,-10
4503,21,2,411.l.85094.t.1,411.p.4503,1,21,79,John Carlson,0.189189,0.702703,0.000000,0.337838,2.500000,0.918919,-58,-30,-30,-50
7174,22,2,411.l.85094.t.5,411.p.7174,5,22,58,Adam Fox,0.098765,0.691358,0.259259,0.345679,1.851852,0.444444,-36,-30,-30,-36
7902,23,2,411.l.85094.t.10,411.p.7902,10,23,21,Brady Tkachuk,0.312500,0.350000,-0.187500,0.175000,3.800000,4.225000,2,2,2,2
5981,24,2,411.l.85094.t.6,411.p.5981,6,16,18,Aleksander Barkov,0.493506,0.649351,0.129870,0.363636,3.415584,0.545455,6,6,6,6

In [20]:
projected_draft[projected_draft.fantasy_team_id == 12]

,pick,round,team_key,player_key,fantasy_team_id,preseason_rank,current_rank,name,G,A,+/-,PPP,SOG,HIT,draft_value,draft_value_clipped,draft_value_clipped_30,draft_value_clipped_50
player_id,,,,,,,,,,,,,,,,,,
6391,7,1,411.l.85094.t.12,411.p.6391,12,8,7,David Pastrnak,0.586667,0.613333,0.226667,0.453333,3.706667,0.720000,0,0,0,0
4682,31,3,411.l.85094.t.12,411.p.4682,12,29,33,Victor Hedman,0.173333,0.600000,0.346667,0.413333,2.506667,0.973333,-2,-2,-2,-2
7905,42,4,411.l.85094.t.12,411.p.7905,12,41,203,Quinn Hughes,0.116883,0.688312,-0.207792,0.376623,1.883117,0.285714,-161,-30,-30,-50
5470,55,5,411.l.85094.t.12,411.p.5470,12,63,70,Johnny Gaudreau,0.345679,0.567901,0.037037,0.308642,2.395062,0.123457,-15,-15,-15,-15
4962,66,6,411.l.85094.t.12,411.p.4962,12,101,25,Tyler Seguin,0.363636,0.467532,0.142857,0.285714,3.688312,1.376623,41,30,30,41
4064,79,7,411.l.85094.t.12,411.p.4064,12,84,68,Kris Letang,0.169014,0.549296,0.211268,0.253521,2.563380,1.690141,11,11,11,11
3641,90,8,411.l.85094.t.12,411.p.3641,12,104,67,Blake Wheeler,0.293333,0.626667,-0.040000,0.333333,2.360000,1.253333,23,23,23,23
4961,103,9,411.l.85094.t.12,411.p.4961,12,123,45,Taylor Hall,0.346667,0.520000,0.186667,0.266667,3.080000,0.653333,58,30,30,50
7110,114,10,411.l.85094.t.12,411.p.7110,12,148,95,Patrik Laine,0.400000,0.426667,-0.160000,0.320000,3.053333,0.920000,19,19,19,19
4002,151,13,411.l.85094.t.12,411.p.4002,12,161,106,Claude Giroux,0.272727,0.519481,0.064935,0.259740,2.402597,0.584416,45,30,30,45
3981,162,14,411.l.85094.t.12,411.p.3981,12,177,118,Jonathan Toews,0.301370,0.465753,0.027397,0.232877,2.835616,0.712329,44,30,30,44
5987,186,16,411.l.85094.t.12,411.p.5987,12,339,179,Rasmus Ristolainen,0.077922,0.324675,-0.116883,0.155844,1.636364,3.623377,7,7,7,7

In [19]:
projected_draft.groupby(['fantasy_team_id']).agg({'draft_value_clipped_50': 'sum'})

                 draft_value_clipped_50
fantasy_team_id
1                                   -92
2                                  -203
3                                    76
4                                     2
5                                  -199
6                                  -125
7                                  -163
8                                   178
9                                  -128
10                                  -85
11                                  -43
12                                  173

In [16]:
scoreboard = manager.lg.scoreboard()