In [32]:
import pandas as pd
from csh_fantasy_bot.projections.fantasypros_nfl import get_projections
projections = pd.read_csv("2021-mdgc-predictions.csv", converters={"position": lambda x: x.strip("[]").replace('"', "").replace("'", "").replace(" ", "").split(",")})
projections['team'] = projections['team'].str.upper()
projections

,name,position,player_id,GP,Bye,fan_points,overall_rank,percent_rostered,pass_yds,pass_td,pass_int,pass_sack,rush_attempts,rush_yards,rush_tds,receiving_targets,receiving_receptions,receiving_yards,receiving_tds,team
0,Patrick Mahomes,[QB],30123,17,12,427.35,29,100%,5547.0,44.0,6.9,29.7,51.0,305.0,2.9,0.0,0.0,0.0,0.0,KC
1,Josh Allen,[QB],30977,17,7,425.08,35,100%,4929.0,38.4,13.2,30.7,84.9,591.0,7.0,0.0,0.0,0.0,0.0,BUF
2,Christian McCaffrey,[RB],30121,17,13,409.03,1,100%,0.0,0.0,0.0,0.0,309.0,1375.0,12.2,150.0,118.0,1030.0,5.4,CAR
3,Kyler Murray,[QB],31833,17,12,401.60,54,100%,4557.0,31.8,14.3,36.8,120.0,790.0,7.3,0.0,0.0,0.0,0.0,ARI
4,Russell Wilson,[QB],25785,17,9,385.46,66,100%,5051.0,37.9,13.3,39.9,68.1,500.0,2.0,0.0,0.0,0.0,0.0,SEA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,New York,[DEF],100020,17,6,71.53,304,1%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NYJ
328,Las Vegas,[DEF],100013,17,8,71.07,2056,1%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LV
329,Cincinnati,[DEF],100004,17,10,70.37,2052,1%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIN
330,Detroit,[DEF],100008,17,9,62.46,2259,0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DET
331,Houston,[DEF],100034,17,10,57.33,339,1%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HOU

In [ ]:
fp_projections = get_projections()

In [ ]:

fp_df = pd.DataFrame(fp_projections)
fp_df.rename(columns={"rank": "fp_rank"}, inplace=True)
fp_df.set_index(['name', 'team'])

In [33]:

yahoo = projections.set_index(['name', 'team'])

fp = fp_df.set_index(['name','team'])

In [38]:
combined = pd.concat([yahoo, fp], axis=1)
combined.iloc[3]

position                   [RB]
player_id               30295.0
GP                         17.0
Bye                        13.0
fan_points               292.66
overall_rank                7.0
percent_rostered           100%
pass_yds                    0.0
pass_td                     0.0
pass_int                    0.0
pass_sack                   0.0
rush_attempts             249.0
rush_yards               1202.0
rush_tds                   11.3
receiving_targets          81.8
receiving_receptions       63.1
receiving_yards           563.0
receiving_tds               2.6
fp_rank                     6.0
position_rank               RB6
Name: (Aaron Jones, GB), dtype: object

                            fp_rank position_rank
name                  team
Christian McCaffrey   CAR         1           RB1
Dalvin Cook           MIN         2           RB2
Alvin Kamara          NO          3           RB3
Derrick Henry         TEN         4           RB4
Ezekiel Elliott       DAL         5           RB5
Aaron Jones           GB          6           RB6
Davante Adams         GB          7           WR1
Tyreek Hill           KC          8           WR2
Saquon Barkley        NYG         9           RB7
Nick Chubb            CLE        10           RB8
Jonathan Taylor       IND        11           RB9
Stefon Diggs          BUF        12           WR3
Austin Ekeler         LAC        13          RB10
Travis Kelce          KC         14           TE1
Calvin Ridley         ATL        15           WR4
DeAndre Hopkins       ARI        16           WR5
Antonio Gibson        WAS        17          RB11
Najee Harris          PIT        18          RB12
D.K. Metcalf          SEA        19           WR6
Joe Mixon             CIN        20          RB13
Justin Jefferson      MIN        21           WR7
A.J. Brown            TEN        22           WR8
Darren Waller         LV         23           TE2
Keenan Allen          LAC        24           WR9
Clyde Edwards-Helaire KC         25          RB14